client_id = "c4ecbd02835e553520eec62af072c81a"
name = "PriceBoost - Bulk Price Editor"
handle = "PriceBoost"
application_url = "https://pricebooster-app-hkfq8.ondigitalocean.app"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true


[webhooks]
api_version = "2025-07"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact", "app/uninstalled"]
uri = "https://pricebooster-app-hkfq8.ondigitalocean.app/webhooks"

[access_scopes]
scopes = "read_products,write_products"

[auth]
redirect_urls = [
    "https://pricebooster-app-hkfq8.ondigitalocean.app/auth/callback",
    "https://pricebooster-app-hkfq8.ondigitalocean.app/auth/shopify/callback",
    "https://pricebooster-app-hkfq8.ondigitalocean.app/api/auth/callback"]

[pos]
embedded = false

# [app_proxy]
url = "https://priceboost-app-l9vn6.ondigitalocean.app"
subpath = "apps/dynamic-pricing"

# URLs légales pour l'App Store
privacy_policy_url = "https://pricebooster-app-hkfq8.ondigitalocean.app/privacy-policy"
terms_of_service_url = "https://pricebooster-app-hkfq8.ondigitalocean.app/terms-of-service"
support_url = "https://pricebooster-app-hkfq8.ondigitalocean.app/support"
